---
- hosts: all
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/tools/sbin:/opt/tools/bin"
  tasks:
   - name: Install Znapzend
     pkgin: name=znapzend state=absent
   - cron:
       name: "Scrub zones twice a month"
       minute: "0"
       hour: "3"
       day: "1,15"
       job: "/usr/sbin/zpool scrub zones"
