---
##########################
- hosts: smartos
  environment:
    PATH: "{{ ansible_env.PATH }}:/opt/tools/sbin:/opt/tools/bin"
  tasks:
   - cron:
       name: "Scrub zones twice a month"
       minute: "0"
       hour: "3"
       day: "1,15"
       job: "/usr/sbin/zpool scrub zones"

##########################
- hosts: omnios
  tasks:
   - package:
       name: rsync
       state: installed

- hosts: nas.internal.coolpeople.us
  roles:
    - cifs_server
