---
- hosts: sambadc.zone
  vars:
    - enable_dhcp_services: false
    - samba_create_domain_controller: true
    - samba_create_domain_users: false  #defines if users defined in samba_domain_users list should be created
    - samba_server_role: 'active directory domain controller'  #defines server role...(standalone server or active directory domain controller)
    - samba_ad_info: { kerberos_realm: coolpeople.us, netbios_domain_name: COOLPEOPLE, dns_forwarder: 10.0.0.1, adminpass: Iwboj15! }
  roles:
    - role: ansible-isc-dhcp
      when: enable_dhcp_services is defined and enable_dhcp_services
    - role: ansible-ntp
    - role: ansible-samba
  pre_tasks:
    - name: Update APT Cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

- hosts: plex.zone
  roles:
    - plexmediaserver

- hosts: nas.zone
  roles:
    - cifs_server
  tasks:
    # Create groups
    - group:
        name: "{{ item.name }}"
        state: present
        gid: "{{ item.gid }}"
      with_items: "{{ host_groups_present }}"
    
    # Remove groups
    - group:
        name: "{{ item.name }}"
        state: absent
      with_items: "{{ host_groups_absent }}"

    # Create users
    - user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        groups: "{{ item.groups }}"
        password: "{{ item.password }}"
        state: present
      with_items: "{{ host_users_present }}"

    # Create ZFS filesystems
    - name: Creating ZFS filesystems.
      zfs:
        name: "{{ item.name }}"
        state: present
#        casesensitivity: "{{ item.casesensitivity }}"
        quota: "{{ item.quota }}"
        mountpoint: "{{ item.mountpoint }}"
      with_items: "{{ zfs_filesystems_present }}"
    - name: Set Directory Properties
      file:
        path: "{{ item.mountpoint }}"
        state: directory
        mode: 0777
      with_items: "{{ zfs_filesystems_present }}"

    # Create SMB Shares
    - name: Creating SMB shares.
      shell: 'sharemgr show | grep "{{ item.path }}" || { sharemgr add-share -r "{{ item.name }}" -s "{{ item.path }}" smb && echo "Share Added"; }'
      register: sharemgr_output
      changed_when: '"Share Added" in sharemgr_output.stdout'
      with_items: "{{ smb_shares_present }}"