---
- name: "Ensure Ubuntu KVM OS image exists ({{ubuntu_kvm_zone_purpose}})"
  imgadm: uuid="{{ ubuntu_kvm_zone_image_uuid }}" state=present

- name: "Ensure Ubuntu KVM Zone ({{ubuntu_kvm_zone_purpose}})"
  vmadm:
    state: present
    brand: "kvm"
    kernel_version: 4.2
    alias: "{{ ubuntu_kvm_zone_alias }}"
    ram: "{{ ubuntu_kvm_zone_ram }}"
    vcpus: "{{ ubuntu_kvm_zone_vcpus }}"
    disks:
      - model: virtio
        boot: true
        image_uuid: "{{ ubuntu_kvm_zone_image_uuid }}"
    nics:
      - nic_tag: external
        model: virtio
        ip: "{{ ubuntu_kvm_zone_ip }}"
        netmask: "{{ ubuntu_kvm_zone_netmask }}"
        gateway: "{{ ubuntu_kvm_zone_gateway }}"
        primary: true
    resolvers: "{{ ubuntu_kvm_zone_dns_resolvers }}"
    quota: "{{ ubuntu_kvm_zone_quota_in_gb }}"
    customer_metadata:
      root_authorized_keys: "{{ root_authorized_keys }}"
      user-script : "/usr/sbin/mdata-get root_authorized_keys > ~root/.ssh/authorized_keys"
