---
- name: Create supervise configuration for Consul Server
  template: src=supervisor.j2 dest=/etc/supervisor/conf.d/consul.conf
  notify: Restart Consul

- meta: flush_handlers
  
- block:
  - name: Retrieve Cluster Member list
    command: consul members
    register: consul_members
    changed_when: false

  - name: Ensure Cluster Joined
    command: "/usr/local/bin/consul join {{ consul_server_leader_ip_address }}" 
    when: "consul_server_leader_ip_address not in consul_members.stdout"

  when: "hostvars[inventory_hostname]['ansible_default_ipv4']['address'] != consul_server_leader_ip_address"
