---
redis_datastore_zone_alias: "redis"
redis_datastore_zone_image_uuid: "23b267fc-ad02-11e7-94da-53e3d3884fe0"
redis_datastore_zone_cpu_cap: 100
redis_datastore_zone_memory_size: 2048
redis_datastore_zone_quota_in_gb: 80
redis_datastore_zone_ip: 192.168.10.13
redis_datastore_zone_netmask: "{{ network_netmask | default('255.255.255.0') }}"
redis_datastore_zone_gateway: "{{ network_gateway | default('192.168.10.1') }}"
redis_datastore_zone_dns_resolvers: "{{ network_dns_resolvers }}"
