---
- name: "Ensure Illumos Zone Image Exists ({{illumos_zone_purpose}})"
  imgadm: uuid="{{ illumos_zone_image_uuid }}" state=present

- name: "Ensure Illumos Zone Exists ({{illumos_zone_purpose}})"
  vmadm:
    state: present
    brand: joyent
    kernel_version: "{{ illumos_zone_kernel_version | default(omit) }}"
    alias: "{{ illumos_zone_alias }}"
    uuid: "{{ illumos_zone_uuid | default(omit) }}"
    image_uuid: "{{ illumos_zone_image_uuid }}"
    max_physical_memory: "{{ illumos_zone_memory_size }}"
    cpu_cap: "{{ illumos_zone_cpu_cap }}"
    nics:
      - nic_tag: "{{ illumos_zone_nic_tag }}"
        ip: "{{ illumos_zone_ip }}"
        netmask: "{{ illumos_zone_netmask }}"
        gateway: "{{ illumos_zone_gateway }}"
        primary: true
    resolvers: "{{ illumos_zone_dns_resolvers }}"
    quota: "{{ illumos_zone_quota_in_gb }}"
    customer_metadata:
      root_authorized_keys: "{{ root_authorized_keys }}"
      user-script : "/usr/sbin/mdata-get root_authorized_keys > ~root/.ssh/authorized_keys"
    