---
- name: Update APT Cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  changed_when: false

- name: Installing Samba4 Packages (Ubuntu)
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - samba
    - samba-common
    - krb5-config
    - krb5-user
    - libnss-winbind
    - libpam-winbind
    - winbind

- name: Creating Kerberos Configuration (Ubuntu)
  template:
    src: etc/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart smbd
    - restart nmbd

- name: Creating smb.conf (Ubuntu)
  template:
    src: etc/smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart smbd
    - restart nmbd
