---
- name: Installing Samba4 Packages (SmartOS)
  pkgin:
    name: "{{ item }}"
    state: present
  with_items:
    - samba

- name: Creating Kerberos Configuration (SmartOS)
  template:
    src: etc/krb5.conf.j2
    dest: /etc/krb5/krb5.conf
    owner: root
    group: root
    mode: 0644
  become: true
  notify:
    - restart smbd
    - restart nmbd

- name: Creating smb.conf (SmartOS)
  template:
    src: etc/smb.conf.j2
    dest: /opt/local/etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart smbd
    - restart nmbd
