---
- name: "Ensure Ubuntu LX Zone Image exists ({{ubuntu_lx_zone_purpose}})"
  imgadm: uuid="{{ ubuntu_lx_zone_image_uuid }}" state=present

- name: "Ensure Ubuntu LX Zone Created ({{ubuntu_lx_zone_purpose}})"
  vmadm:
    state: present
    brand: "lx"
    kernel_version: "{{ ubuntu_lx_zone_kernel_version | default(omit) }}"
    alias: "{{ ubuntu_lx_zone_alias }}"
    uuid: "{{ ubuntu_lx_zone_uuid | default(omit) }}"
    image_uuid: "{{ ubuntu_lx_zone_image_uuid }}"
    max_physical_memory: "{{ ubuntu_lx_zone_memory_size }}"
    cpu_cap: "{{ ubuntu_lx_zone_cpu_cap }}"
    nics:
      - nic_tag: external
        ip: "{{ ubuntu_lx_zone_ip }}"
        netmask: "{{ ubuntu_lx_zone_netmask }}"
        gateway: "{{ ubuntu_lx_zone_gateway }}"
        primary: true
    resolvers: "{{ ubuntu_lx_zone_dns_resolvers }}"
    quota: "{{ ubuntu_lx_zone_quota_in_gb }}"
    customer_metadata:
      root_authorized_keys: "{{ root_authorized_keys }}"
      user-script : "/usr/sbin/mdata-get root_authorized_keys > ~root/.ssh/authorized_keys"
    