---
- name: Ensure RabbitMQ OS image exists
  imgadm: uuid="{{ rabbitmq_server_zone_image_uuid }}" state=present

- name: Ensure RabbitMQ Server Zone
  vmadm:
    state: present
    brand: "{{ rabbitmq_server_zone_brand | default('joyent') }}"
    kernel_version: "{{ rabbitmq_server_zone_kernel_version | default(omit) }}"
    alias: "{{ rabbitmq_server_zone_alias }}"
    uuid: "{{ rabbitmq_server_zone_uuid | default(omit) }}"
    image_uuid: "{{ rabbitmq_server_zone_image_uuid }}"
    max_physical_memory: "{{ rabbitmq_server_zone_memory_size }}"
    cpu_cap: "{{ rabbitmq_server_zone_cpu_cap }}"
    nics:
      - nic_tag: external
        ip: "{{ rabbitmq_server_zone_ip }}"
        netmask: "{{ rabbitmq_server_zone_netmask }}"
        gateway: "{{ rabbitmq_server_zone_gateway }}"
        primary: true
    resolvers: "{{ rabbitmq_server_zone_dns_resolvers }}"
    quota: "{{ rabbitmq_server_zone_quota_in_gb }}"
    customer_metadata:
      root_authorized_keys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDYIHv3DoXnAMn+dggUup1a+jjSqpZiIU5ThgljXHG9KM+iy1W3zo9qshUE7vBj/l7l5aHzRKyXsmWb6EdmtlVBnYl7SH5IMGaEFlB6n7T+yoMRl7VczZZxvP+VSAac2HeLPvdrCDeJCckfkHeTg9E3rt2PcAz0REKDCm34lpsedgM4QrVh8D54NgqLCdpT+QpidEBwE1T5wGMId4OwBB+r1VJZyn+lstJreQ0mu67qn3TFKu5AxZoTdDj6BSDqqHEos5KirS4pz3zt3r5IbC3mv8vDm9+o6O5M2f7R6RRNfD9IPJANmO0k2Ajf529I0bGgAGgIpIXb8OaI6G+L48dR john@Johns-MacBook-Pro.local"
      user-script : "/usr/sbin/mdata-get root_authorized_keys > ~root/.ssh/authorized_keys"
    