---
zone_uuid: "6a8672ee-d3d6-442b-bbfb-9ced5bfb1327"
host_groups_present: 
  - name: users
    gid: 12000

host_groups_absent: 
  - name: dudes

host_users_present:
  - name: john
    uid: 15001
    groups: "users"   # comma separated
    password: $6$OdGlBONSeAlpz1Y2$6ppqG/HmSVIhGDvZQLRrPycOy6F1nv22lHezXpkW1xkJ9oDEBK78wn0ov6M1m9Pq7x9Dehr7RgTcGKfW2q63N1
 
host_users_absent:
  - name: unused

zfs_filesystems_present:
  - name: "zones/{{ zone_uuid }}/data/media"
    state: present
    casesensitivity: insensitive
    quota: none
    mountpoint: /media

  - name: "zones/{{ zone_uuid }}/data/photography"
    state: present
    casesensitivity: insensitive
    quota: none
    mountpoint: /photography

smb_shares_present:
  - name: Media
    path: /media

  - name: Photography
    path: /photography
